// Exercise the production HTML renderer without a browser or ledger writes.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const web=path.resolve(__dirname,'../src/invoice_print_layout/web');
const helpers=fs.readFileSync(path.join(web,'app.js'),'utf8').split(/\r?\n/).filter(x=>x.startsWith('const esc=')||x.startsWith('const money=')).join('\n');
const source=fs.readFileSync(path.join(web,'report.js'),'utf8').split('const previewButton=')[0];
const ctx={URL,location:{origin:'http://127.0.0.1:8765'}};vm.createContext(ctx);
vm.runInContext(helpers+'\n'+source,ctx);
const item=(id,title,cents,project='项目一')=>({id,title,amount_cents:cents,category:'材料采购',project,stage:'draft',attachments:[{id:'file-'+id,name:id+'.pdf',role:'invoice',available:true}]});
const items=[item('rain1','甲店 · 雨衣',8870),item('mask','口罩采购（50只）',2460),item('rain2','乙店 · 雨衣采购（33件）',2870)];
const before=JSON.stringify(items);
const render=items=>ctx.buildReportPreviewHtml(items);
const cell=(html,id)=>html.match(new RegExp('data-cell="'+id+'">([\\s\\S]*?)</(?:td|th)>'))[1].replace(/<[^>]+>/g,'');
const html=render(items);
assert.equal(cell(html,'H24'),'117.40');
assert.equal(cell(html,'H25'),'24.60');
assert.equal(cell(html,'H26'),'');
assert.equal(cell(html,'H35'),'142.00');
assert.equal((cell(html,'B24').match(/雨衣采购/g)||[]).length,1);
assert.equal((html.match(/<article class="expense"/g)||[]).length,3);
for(const x of items)assert.ok(html.includes('/file/file-'+x.id));
assert.equal(JSON.stringify(items),before);
const separate=render([items[0],{...items[2],project:'项目二'}]);
assert.equal(cell(separate,'H24'),'88.70');assert.equal(cell(separate,'H25'),'28.70');
assert.equal(cell(render([items[2]]),'H24'),'28.70');
const overflow=render([...Array.from({length:5},(_,i)=>item('other'+i,'工具'+i,100)),...items]);
assert.equal(cell(overflow,'H28'),'143.00');assert.equal(cell(overflow,'H35'),'147.00');
assert.match(cell(overflow,'B28'),/工具4/);assert.match(cell(overflow,'B28'),/口罩采购/);
assert.equal((cell(overflow,'B28').match(/雨衣采购/g)||[]).length,1);
console.log('passed: combined raincoats, retained originals, separate projects, filtered selection, overflow and totals');
