(()=>{
  'use strict';
  const $=id=>document.getElementById(id),project=new URLSearchParams(location.search).get('project')||'';
  let token='',config=null,matched=null,busy=false;
  const node=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
  async function post(action,body){const r=await fetch('/api/photos/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:JSON.stringify({...body,project_id:project})});const d=await r.json();if(!r.ok)throw Error(d.error||'操作未完成');return d;}
  function links(where,item){const preview=node('a','查看预览'),download=node('a','下载 PPTX');preview.href=item.preview;preview.target='_blank';preview.rel='noopener';download.href=item.download;download.download='卸货日报.pptx';where.append(preview,document.createTextNode('　'),download);}
  function enable(){const complete=matched&&!matched.issues.length&&[...$('dailySlots').querySelectorAll('select')].every(s=>s.value);$('dailyGenerate').disabled=busy||!complete;$('dailyMatch').disabled=busy;}
  async function load(){try{const r=await fetch('/api/daily-reports?project='+encodeURIComponent(project));config=await r.json();if(!r.ok)throw Error(config.error||'模板读取失败');token=config.token;$('dailyForm').hidden=!config.available;if(!config.available){$('dailyInfo').textContent='本项目尚未配置日报模板。';return;}$('dailyInfo').textContent=config.name+'。'+config.fixed_content+' 工厂照片按运输批次配对，保留实际拍摄日期；此前工时请填写已确认值。';if(!$('dailyDate').value){$('dailyDate').value=config.first_day;$('dailyStart').value=config.default_start;$('dailyEnd').value=config.default_end;$('dailyPrior').value='0';}$('dailyHistory').replaceChildren();for(const row of config.reports){const p=node('p',row.date+' · 当日 '+row.hours+' 小时　');links(p,row);$('dailyHistory').append(p);}}catch(e){$('dailyStatus').textContent=e.message;}}
  $('dailyReports').addEventListener('toggle',()=>{if($('dailyReports').open)load();});
  $('dailyDate').onchange=()=>{matched=null;$('dailySlots').replaceChildren();$('dailyIssues').textContent='日期已改变，请重新配图。';$('dailyPrior').value=$('dailyDate').value===config?.first_day?'0':'';$('dailyConfirmed').checked=false;enable();};
  $('dailyMatch').onclick=async()=>{busy=true;enable();$('dailyStatus').textContent='正在匹配已归档车头照片…';try{matched=await post('daily-match',{date:$('dailyDate').value});$('dailySlots').replaceChildren();for(const slot of matched.slots){const card=node('article');card.className='card';card.append(node('p',(slot.plate||'车辆待补充')+' · '+slot.place));const select=node('select');select.dataset.slot=slot.key;select.setAttribute('aria-label',(slot.plate||'待补充')+' '+slot.place+'车头照片');select.append(new Option(slot.message,''));for(const c of slot.candidates)select.append(new Option(c.date+' · '+c.label+' · '+c.quality,c.id));select.value=slot.selected;const image=node('img');image.alt=(slot.plate||'')+' '+slot.place+'车头';const display=()=>{image.hidden=!select.value;if(select.value)image.src='/photo-file/'+encodeURIComponent(project)+'/'+select.value;else image.removeAttribute('src');enable();};select.onchange=display;display();card.append(select,image);$('dailySlots').append(card);}$('dailyIssues').textContent=[...matched.issues,matched.scope].join(' ');$('dailyStatus').textContent='配图完成，请核对照片及固定内容。';$('dailyConfirmed').checked=false;}catch(e){matched=null;$('dailyStatus').textContent=e.message;}finally{busy=false;enable();}};
  $('dailyForm').onsubmit=async event=>{event.preventDefault();if(busy||!matched)return;busy=true;enable();$('dailyResult').replaceChildren();$('dailyStatus').textContent='正在生成并用 PowerPoint 检查，完成后显示预览和下载入口…';const selections=Object.fromEntries([...$('dailySlots').querySelectorAll('select')].map(s=>[s.dataset.slot,s.value]));try{const result=await post('daily-generate',{date:$('dailyDate').value,start:$('dailyStart').value,end:$('dailyEnd').value,prior_hours:$('dailyPrior').value,selections,confirmed:$('dailyConfirmed').checked});links($('dailyResult'),result);$('dailyStatus').textContent=`已通过 PowerPoint 检查 · 当日 ${result.values.hours} 小时 · 累计 ${result.values.cumulative} 小时`;await load();}catch(e){$('dailyStatus').textContent=e.message;}finally{busy=false;enable();}};
})();
